export const languageAcronyms: { [key: string]: string } = {
  "Afrikaans": "AF",
  "Albanian": "SQ",
  "Amharic": "AM",
  "Arabic": "AR",
  "Armenian": "HY",
  "Azerbaijani": "AZ",
  "Basque": "EU",
  "Belarusian": "BE",
  "Bengali": "BN",
  "Bosnian": "BS",
  "Bulgarian": "BG",
  "Burmese": "MY",
  "Catalan": "CA",
  "Cebuano": "CEB",
  "Chichewa": "NY",
  "Chinese (Cantonese)": "YUE",
  "Chinese (Mandarin)": "ZH",
  "Croatian": "HR",
  "Czech": "CS",
  "Danish": "DA",
  "Dutch": "NL",
  "English": "EN",
  "Esperanto": "EO",
  "Estonian": "ET",
  "Filipino": "FIL",
  "Finnish": "FI",
  "French": "FR",
  "Galician": "GL",
  "Georgian": "KA",
  "German": "DE",
  "Greek": "EL",
  "Gujarati": "GU",
  "Haitian Creole": "HT",
  "Hausa": "HA",
  "Hawaiian": "HAW",
  "Hebrew": "HE",
  "Hindi": "HI",
  "Hmong": "HMN",
  "Hungarian": "HU",
  "Icelandic": "IS",
  "Igbo": "IG",
  "Indonesian": "ID",
  "Irish": "GA",
  "Italian": "IT",
  "Japanese": "JA",
  "Javanese": "JV",
  "Kannada": "KN",
  "Kazakh": "KK",
  "Khmer": "KM",
  "Korean": "KO",
  "Kurdish": "KU",
  "Kyrgyz": "KY",
  "Lao": "LO",
  "Latin": "LA",
  "Latvian": "LV",
  "Lithuanian": "LT",
  "Luxembourgish": "LB",
  "Macedonian": "MK",
  "Malagasy": "MG",
  "Malay": "MS",
  "Malayalam": "ML",
  "Maltese": "MT",
  "Maori": "MI",
  "Marathi": "MR",
  "Mongolian": "MN",
  "Nepali": "NE",
  "Norwegian": "NO",
  "Pashto": "PS",
  "Persian (Farsi)": "FA",
  "Polish": "PL",
  "Portuguese": "PT",
  "Punjabi": "PA",
  "Romanian": "RO",
  "Russian": "RU",
  "Samoan": "SM",
  "Scots Gaelic": "GD",
  "Serbian": "SR",
  "Sesotho": "ST",
  "Shona": "SN",
  "Sindhi": "SD",
  "Sinhala": "SI",
  "Slovak": "SK",
  "Slovenian": "SL",
  "Somali": "SO",
  "Spanish": "ES",
  "Sundanese": "SU",
  "Swahili": "SW",
  "Swedish": "SV",
  "Tajik": "TG",
  "Tamil": "TA",
  "Telugu": "TE",
  "Thai": "TH",
  "Turkish": "TR",
  "Ukrainian": "UK",
  "Urdu": "UR",
  "Uzbek": "UZ",
  "Vietnamese": "VI",
  "Welsh": "CY",
  "Xhosa": "XH",
  "Yiddish": "YI",
  "Yoruba": "YO",
  "Zulu": "ZU"
};

export function getLanguageAcronym(language: string): string {
    return languageAcronyms[language] || language;
  }