import { SelectItem } from "@/components/ui/select"

export default function Languages() {
    return (
        <>
            <SelectItem value="Afrikaans">Afrikaans</SelectItem>
            <SelectItem value="Albanian">Albanian</SelectItem>
            <SelectItem value="Amharic">Amharic</SelectItem>
            <SelectItem value="Arabic">Arabic</SelectItem>
            <SelectItem value="Armenian">Armenian</SelectItem>
            <SelectItem value="Azerbaijani">Azerbaijani</SelectItem>
            <SelectItem value="Basque">Basque</SelectItem>
            <SelectItem value="Belarusian">Belarusian</SelectItem>
            <SelectItem value="Bengali">Bengali</SelectItem>
            <SelectItem value="Bosnian">Bosnian</SelectItem>
            <SelectItem value="Bulgarian">Bulgarian</SelectItem>
            <SelectItem value="Burmese">Burmese</SelectItem>
            <SelectItem value="Catalan">Catalan</SelectItem>
            <SelectItem value="Cebuano">Cebuano</SelectItem>
            <SelectItem value="Chichewa">Chichewa</SelectItem>
            <SelectItem value="Chinese (Cantonese)">Chinese (Cantonese)</SelectItem>
            <SelectItem value="Chinese (Mandarin)">Chinese (Mandarin)</SelectItem>
            <SelectItem value="Croatian">Croatian</SelectItem>
            <SelectItem value="Czech">Czech</SelectItem>
            <SelectItem value="Danish">Danish</SelectItem>
            <SelectItem value="Dutch">Dutch</SelectItem>
            <SelectItem value="English">English</SelectItem>
            <SelectItem value="Esperanto">Esperanto</SelectItem>
            <SelectItem value="Estonian">Estonian</SelectItem>
            <SelectItem value="Filipino">Filipino</SelectItem>
            <SelectItem value="Finnish">Finnish</SelectItem>
            <SelectItem value="French">French</SelectItem>
            <SelectItem value="Galician">Galician</SelectItem>
            <SelectItem value="Georgian">Georgian</SelectItem>
            <SelectItem value="German">German</SelectItem>
            <SelectItem value="Greek">Greek</SelectItem>
            <SelectItem value="Gujarati">Gujarati</SelectItem>
            <SelectItem value="Haitian Creole">Haitian Creole</SelectItem>
            <SelectItem value="Hausa">Hausa</SelectItem>
            <SelectItem value="Hawaiian">Hawaiian</SelectItem>
            <SelectItem value="Hebrew">Hebrew</SelectItem>
            <SelectItem value="Hindi">Hindi</SelectItem>
            <SelectItem value="Hmong">Hmong</SelectItem>
            <SelectItem value="Hungarian">Hungarian</SelectItem>
            <SelectItem value="Icelandic">Icelandic</SelectItem>
            <SelectItem value="Igbo">Igbo</SelectItem>
            <SelectItem value="Indonesian">Indonesian</SelectItem>
            <SelectItem value="Irish">Irish</SelectItem>
            <SelectItem value="Italian">Italian</SelectItem>
            <SelectItem value="Japanese">Japanese</SelectItem>
            <SelectItem value="Javanese">Javanese</SelectItem>
            <SelectItem value="Kannada">Kannada</SelectItem>
            <SelectItem value="Kazakh">Kazakh</SelectItem>
            <SelectItem value="Khmer">Khmer</SelectItem>
            <SelectItem value="Korean">Korean</SelectItem>
            <SelectItem value="Kurdish">Kurdish</SelectItem>
            <SelectItem value="Kyrgyz">Kyrgyz</SelectItem>
            <SelectItem value="Lao">Lao</SelectItem>
            <SelectItem value="Latin">Latin</SelectItem>
            <SelectItem value="Latvian">Latvian</SelectItem>
            <SelectItem value="Lithuanian">Lithuanian</SelectItem>
            <SelectItem value="Luxembourgish">Luxembourgish</SelectItem>
            <SelectItem value="Macedonian">Macedonian</SelectItem>
            <SelectItem value="Malagasy">Malagasy</SelectItem>
            <SelectItem value="Malay">Malay</SelectItem>
            <SelectItem value="Malayalam">Malayalam</SelectItem>
            <SelectItem value="Maltese">Maltese</SelectItem>
            <SelectItem value="Maori">Maori</SelectItem>
            <SelectItem value="Marathi">Marathi</SelectItem>
            <SelectItem value="Mongolian">Mongolian</SelectItem>
            <SelectItem value="Nepali">Nepali</SelectItem>
            <SelectItem value="Norwegian">Norwegian</SelectItem>
            <SelectItem value="Pashto">Pashto</SelectItem>
            <SelectItem value="Persian (Farsi)">Persian (Farsi)</SelectItem>
            <SelectItem value="Polish">Polish</SelectItem>
            <SelectItem value="Portuguese">Portuguese</SelectItem>
            <SelectItem value="Punjabi">Punjabi</SelectItem>
            <SelectItem value="Romanian">Romanian</SelectItem>
            <SelectItem value="Russian">Russian</SelectItem>
            <SelectItem value="Samoan">Samoan</SelectItem>
            <SelectItem value="Scots Gaelic">Scots Gaelic</SelectItem>
            <SelectItem value="Serbian">Serbian</SelectItem>
            <SelectItem value="Sesotho">Sesotho</SelectItem>
            <SelectItem value="Shona">Shona</SelectItem>
            <SelectItem value="Sindhi">Sindhi</SelectItem>
            <SelectItem value="Sinhala">Sinhala</SelectItem>
            <SelectItem value="Slovak">Slovak</SelectItem>
            <SelectItem value="Slovenian">Slovenian</SelectItem>
            <SelectItem value="Somali">Somali</SelectItem>
            <SelectItem value="Spanish">Spanish</SelectItem>
            <SelectItem value="Sundanese">Sundanese</SelectItem>
            <SelectItem value="Swahili">Swahili</SelectItem>
            <SelectItem value="Swedish">Swedish</SelectItem>
            <SelectItem value="Tajik">Tajik</SelectItem>
            <SelectItem value="Tamil">Tamil</SelectItem>
            <SelectItem value="Telugu">Telugu</SelectItem>
            <SelectItem value="Thai">Thai</SelectItem>
            <SelectItem value="Turkish">Turkish</SelectItem>
            <SelectItem value="Ukrainian">Ukrainian</SelectItem>
            <SelectItem value="Urdu">Urdu</SelectItem>
            <SelectItem value="Uzbek">Uzbek</SelectItem>
            <SelectItem value="Vietnamese">Vietnamese</SelectItem>
            <SelectItem value="Welsh">Welsh</SelectItem>
            <SelectItem value="Xhosa">Xhosa</SelectItem>
            <SelectItem value="Yiddish">Yiddish</SelectItem>
            <SelectItem value="Yoruba">Yoruba</SelectItem>
            <SelectItem value="Zulu">Zulu</SelectItem>
        </>
    )
}